#!/bin/bash
#SBATCH -J tmswift_4096         # job name
#SBATCH -o tmswift_4096.o%j       # output and error file name (%j expands to jobID)
#SBATCH -n 4096           # total number of mpi tasks requested
#SBATCH -p normal	     # queue (partition) -- normal, development, etc.
#SBATCH -t 01:00:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=hlammiv@asu.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes
module restore
export SLEPC_DIR=/work/03324/hlammiv/slepc-3.6.0
time ibrun ./tmswift init # run the MPI executable named a.out
